### ISSUE TITLE
Slike za README

### ISSUE THREAD

**Issue by jus-kosmac** [jus-kosmac/PSA1#1]
![graf1](https://cloud.githubusercontent.com/assets/13056585/21294588/753710be-c540-11e6-9de7-9f9494fbd323.png)

![graf2](https://cloud.githubusercontent.com/assets/13056585/21294589/80555c9e-c540-11e6-9cbd-1b07fd183025.png)

**Comment by jaanos** [comment]
Slike lahko tudi dodaš v repozitorij in se potem iz `README.md` nanje relativno sklicuješ (npr. če so v isti mapi, se nanje sklicuješ kar z imenom datoteke).

**Comment by jus-kosmac** [comment]
Sem dodal slike v repozitorij.
